# Generated by Django 4.2 on 2023-09-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlideShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Heading', models.CharField(max_length=50)),
                ('RegisteredDate', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='slideshow/')),
            ],
        ),
    ]
